import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import wordList from '../wordList.json'

const inter = Inter({ subsets: ['latin'] })

type WordList = {
  id: number;
  word: string;
}

const onClickButton = () => {
  const homeText = document.querySelector('.js-word');
  if (homeText) {
    const randomWord = wordList[Math.floor(Math.random() * wordList.length)];
    homeText.textContent = randomWord.word;
  }
}

// click c-link and reset home text and your name and input name
const onClickLink = () => {
  const homeText = document.querySelector('.js-word');
  if (homeText) {
    homeText.textContent = '';
  }
  const yourName = document.querySelector('.js-your-name');
  if (yourName) {
    yourName.textContent = '名前を入れてボタンをクリックしてください。';
  }
  const inputName = document.querySelector('.c-input-area') as HTMLInputElement;
  if (inputName) {
    inputName.value = '';
  }
}



// click button and show input word in js-your-name
const onClickButton2 = () => {
  const yourName = document.querySelector('.js-your-name');
  if (yourName) {
    const inputName = document.querySelector('.c-input-area') as HTMLInputElement;
    if (inputName) {
      yourName.textContent = inputName.value;
    }
  }
}




export default function Home() {
  return (
    <>
      <Head>
        <title>ほめらにあん。 | あなたを褒めるポメラニアン</title>
        <meta name="ほめらにあん。 | 名前を入力してボタンをクリック！あなたを褒めてくれるポメラニアンのWebサービス" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic:wght@300;400;500;700;900&display=swap" rel="stylesheet" />
      </Head>
      <main>
        <header>
          <h1 className="c-header__title">ほめらにあん。</h1>
          <p className="c-header__text">あなたを褒める、ポメラニアン</p>
        </header>
        
        <div className="l-container">
          <div className="l-word-area">
            <p className="js-your-name c-text__your-name">名前を入れてボタンをクリックしてください。</p>
            <p className="js-word c-text__home-word"></p>
          </div>
          <Image
            src="/image01.png"
            alt="ポメラニアンのイラスト"
            width={160}
            height={204}
            priority
            className="c-image"
          />
          <div className="flex-box">
            <input className="c-input-area" type="text" placeholder="あなたの名前を入力してください" />
            <div className="button-area">
              <button className="c-button" onClick={() => {onClickButton(); onClickButton2();}}>ぽめまるに褒めてもらう</button>
            </div>
            <p className="c-text-reset" onClick={onClickLink}>リセットする</p>
          </div>
        </div>

        <small className="c-text__copyright">&copy; 2023 ほめらにあん。 by R.YUKI Portfolio</small>
      </main>
    </>
  )
}
